version: "3.8"
services:
  api:
    build: .
    ports:
      - "8002:8002"
    env_file:
      - .env
    volumes:
      - ./results:/app/results
    depends_on:
      - matrix
  matrix:
    image: matrixdotorg/synapse:latest
    environment:
      - SYNAPSE_SERVER_NAME=matrix.local
    ports:
      - "8008:8008"
  aries:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.2
    ports:
      - "8020:8020"
