name: Deploy to CIRIS Node (Prod)

on:
  push:
    branches:
      - main
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Build Application
      run: npm run build

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H node0.ciris.ai >> ~/.ssh/known_hosts

    - name: Deploy Code to node0.ciris.ai
      run: |
        rsync -avz --delete ./ root@node0.ciris.ai:/root/cirisnode/

    - name: Restart Service or Build
      run: |
        ssh root@node0.ciris.ai "cd /root/cirisnode && ./start.sh"
