name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "Debug: List files in the runner environment"
        run: ls -R

      - name: Install dependencies (ignores missing lock file)
        run: npm install --no-audit --no-fund

      - name: Build app
        run: npm run build

      - name: Start app (adjust this step to fit your deploy process)
        run: npm run start
